{
    "name": "Bambora Batch Payment",
    "version": "19.1.1",
    "summary": "Bambora Bank-to-Bank EFT/ACH/Batch Payment",
    "description": "Bambora Bank-to-Bank EFT/ACH/Batch Payment",
    "author": "Syncoria Inc.",
    "website": "https://www.syncoria.com",
    "company": "Syncoria Inc.",
    "maintainer": "Syncoria Inc.",
    "license": "OPL-1",
    "support": "support@syncoria.com",
    "price": 5000,
    "currency": "USD",
    "category": "Accounts",
    "depends": ["account", "payment", "sale", "syncoria_can_payroll"],
    "images": [
        "static/description/banner.png",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/payment_bamboraeft.xml",
        "views/payment_bamboraeft_templates.xml",
        "views/batch_payment_tracking_views.xml",
        # "views/inherited_account_move_views.xml",
        "views/partner_view.xml",
        # "views/sale_order.xml",
        "views/hr_payslip.xml",
        "views/hr_payslip_run.xml",
        "views/report_actions.xml",
        "reports/deposit_summary_report_view.xml",
        "data/journal.xml",
        "data/account_payment_method.xml",
        "data/bamboraeft.xml",
        "data/cron_data.xml",
        "data/custom_email.xml",
        "data/emails/payment_refuse_email.xml",
    ],
    # "assets": {
    #         "web.assets_frontend": [
    #             "bambora_batch_payment/static/src/js/payment_form.js",
    #         ],
    # },
    "application": True,
    "pre_init_hook": "pre_init_check",
    "uninstall_hook": "uninstall_hook",
}
