{
    "name": "Bambora Batch Payment",
    "version": "17.0.1.0.0",
    "category": "Accounts",
    "summary": "Bambora Bank-to-Bank EFT/ACH/Batch Payment",
    "author": "Syncoria Inc.",
    "website": "https://www.syncoria.com",
    "company": "Syncoria Inc.",
    "maintainer": "Syncoria Inc.",
    "depends": ["account", "payment", "sale","syncoria_can_payroll"],
    "images": [
        "static/description/banner.png",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/payment_bamboraeft.xml",
        "views/payment_bamboraeft_templates.xml",
        "views/batch_payment_tracking_views.xml",
        # "views/inherited_account_move_views.xml",
        "views/partner_view.xml",
        # "views/sale_order.xml",
        "views/hr_payslip.xml",
        "views/hr_payslip_run.xml",
        "views/report_actions.xml",
        "reports/deposit_summary_report_view.xml",
        "data/journal.xml",
        "data/account_payment_method.xml",
        "data/bamboraeft.xml",
        "data/cron_data.xml",
        "data/custom_email.xml",
        "data/emails/payment_refuse_email.xml"
    ],
    # "assets": {
    #         'web.assets_frontend': [
    #             'bambora_batch_payment/static/src/js/payment_form.js',
    #         ],
    # },
    "price": 1000,
    "currency": "USD",
    "license": "AGPL-3",
    "support": "support@syncoria.com",
    'application': True,
    "pre_init_hook": "pre_init_check",
    "uninstall_hook": "uninstall_hook",
}
